version: 2.1

#orbs:
#  maven: circleci/maven@0.0.12

jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn clean install -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - store_artifacts:
          path: ~/repo/target/cucumber/index.html
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
          
  
  publish:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run:
          name: Import GnuPG Keys
          command: echo ${GPG_KEY} | base64 --decode | gpg --import --no-tty --batch --yes || true
      - run:
          name: Publish to Maven Central
          command: mvn deploy -s .circleci/.circleci.settings.xml -P release -DskipTests -Dmvn-gpg.passphrase=${GPG_PASSPHRASE} -Dossrh.username=${OSSRH_USERNAME} -Dossrh.password=${OSSRH_PASSWORD}
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}

workflows:
  ci-cd:
    jobs:
      - build
      - test:
          requires:
            - build
      - sonar:
          requires:
            - build
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - sonar
